"""
src/reporting/stakeholder_text.py

Plain-language explanations of each domain's fragility status, written
for a general audience — the same rigor as the technical narrative in
narrative.py, translated into everyday language, not simplified into
false certainty. Deliberately static per (domain, status_id, lang), not
dynamically generated by an LLM: this keeps the output reproducible,
reviewable, and testable like the rest of the pipeline (see planning
discussion — AI-generated summaries were deferred as a separate,
clearly-labeled feature, not folded into the core scorecard).

Writing rules followed throughout:
  - Never predict whether or when a crisis will happen.
  - Never give specific financial advice.
  - Always distinguish "the data shows growing instability" from
    "something bad is happening" — the first is what's measured, the
    second is not implied by it.
"""

STAKEHOLDER_EXPLANATIONS: dict[str, dict[str, dict[str, str]]] = {
    "external_stability": {
        "stable": {
            "es": "El peso y las reservas del país se están comportando de forma predecible. No hay señales, por ahora, de que México esté perdiendo su capacidad de amortiguar un choque externo.",
            "en": "The peso and the country's reserves are behaving predictably. There's no sign, for now, that Mexico is losing its ability to absorb an external shock.",
        },
        "monitor": {
            "es": "El tipo de cambio o las reservas del país muestran algo de inestabilidad reciente. Todavía no es una señal de alarma, pero vale la pena seguirla los próximos meses.",
            "en": "The exchange rate or the country's reserves show some recent instability. This isn't an alarm yet, but it's worth watching over the coming months.",
        },
        "fragile": {
            "es": "El tipo de cambio y/o las reservas internacionales se están moviendo de forma cada vez menos predecible. Esto no significa que vaya a haber una devaluación — significa que el sistema está absorbiendo más presión de la habitual, algo consistente con el entorno externo actual.",
            "en": "The exchange rate and/or international reserves are behaving in an increasingly unpredictable way. This doesn't mean a devaluation is coming — it means the system is absorbing more pressure than usual, consistent with the current external environment.",
        },
    },
    "liquidity": {
        "stable": {
            "es": "La cantidad de dinero circulando en la economía (M1, M2) se está moviendo de forma estable, sin señales de comportamiento errático.",
            "en": "The amount of money circulating in the economy (M1, M2) is moving in a stable way, with no signs of erratic behavior.",
        },
        "monitor": {
            "es": "Los agregados monetarios muestran cierta inestabilidad reciente. No implica, por sí solo, un riesgo de inflación — pero es una variable que vale la pena seguir de cerca.",
            "en": "Monetary aggregates show some recent instability. This alone doesn't imply an inflation risk — but it's a variable worth following closely.",
        },
        "fragile": {
            "es": "El dinero en circulación está creciendo y moviéndose de forma cada vez menos predecible. Esto es justamente la preocupación pública más común sobre política monetaria — vale la pena vigilarla, aunque por sí sola no confirma que vaya a haber más inflación.",
            "en": "Money in circulation is growing and behaving in an increasingly unpredictable way. This is exactly the most common public concern about monetary policy — worth watching, though on its own it doesn't confirm that more inflation is coming.",
        },
    },
    "rates": {
        "stable": {
            "es": "Las tasas de interés se están moviendo de forma predecible. El costo de pedir dinero prestado no muestra señales de volverse más errático.",
            "en": "Interest rates are moving predictably. The cost of borrowing money shows no sign of becoming more erratic.",
        },
        "monitor": {
            "es": "Las tasas de interés muestran algo de inestabilidad reciente. Podría reflejar ajustes normales de política monetaria — no es, por sí sola, una señal de crisis.",
            "en": "Interest rates show some recent instability. This could reflect normal monetary-policy adjustments — on its own, it isn't a crisis signal.",
        },
        "fragile": {
            "es": "Las tasas de interés se están moviendo de forma cada vez menos predecible. Esto puede encarecer créditos, hipotecas y tarjetas con tasa variable — es la señal de este panel más directamente ligada al bolsillo de la gente.",
            "en": "Interest rates are behaving in an increasingly unpredictable way. This can make loans, mortgages, and variable-rate credit more expensive — it's the signal in this panel most directly tied to people's day-to-day finances.",
        },
    },
    "real_economy": {
        "stable": {
            "es": "La actividad económica y el empleo se están comportando de forma estable, sin señales de deterioro.",
            "en": "Economic activity and employment are behaving stably, with no sign of deterioration.",
        },
        "monitor": {
            "es": "El PIB o el desempleo muestran algo de inestabilidad reciente. Vale la pena seguirlo, sin que hoy sea motivo de preocupación.",
            "en": "GDP or unemployment show some recent instability. Worth following, though not a cause for concern today.",
        },
        "fragile": {
            "es": "La actividad económica y/o el empleo se están comportando de forma cada vez menos predecible — la señal más directamente ligada al día a día de las personas (empleos, ingresos).",
            "en": "Economic activity and/or employment are behaving in an increasingly unpredictable way — the signal most directly tied to people's everyday lives (jobs, income).",
        },
    },
    "prices": {
        "stable": {
            "es": "La inflación se está comportando de forma predecible, sin señales de descontrol.",
            "en": "Inflation is behaving predictably, with no sign of getting out of control.",
        },
        "monitor": {
            "es": "Los precios muestran algo de inestabilidad reciente. Vale la pena seguirlo antes de sacar conclusiones.",
            "en": "Prices show some recent instability. Worth following before drawing conclusions.",
        },
        "fragile": {
            "es": "El nivel de precios se está moviendo de forma cada vez menos predecible — relevante porque la inflación afecta directamente el poder de compra de cualquier persona, sin importar su nivel de ingreso.",
            "en": "The price level is moving in an increasingly unpredictable way — relevant because inflation directly affects everyone's purchasing power, regardless of income level.",
        },
    },
}


def get_stakeholder_explanation(domain_key: str, status_id: str, lang: str) -> str:
    """
    Returns the plain-language explanation for a domain at a given
    status. Raises explicitly if the combination is missing, rather
    than silently returning an empty string on the live dashboard.
    """
    try:
        return STAKEHOLDER_EXPLANATIONS[domain_key][status_id][lang]
    except KeyError as e:
        raise KeyError(
            f"No stakeholder explanation for domain='{domain_key}', "
            f"status_id='{status_id}', lang='{lang}'"
        ) from e

# --- Composite-level stakeholder explanations, by status_id and language ---
# Same writing rules as the domain-level explanations above: never
# predict a crisis, never give specific financial advice, always
# distinguish "the data shows growing instability" from "something bad
# is happening now."

COMPOSITE_STAKEHOLDER_EXPLANATIONS: dict[str, dict[str, str]] = {
    "stable": {
        "es": "En conjunto, los indicadores que monitorea este panel se están comportando de forma predecible. No hay, por ahora, una señal generalizada de que la economía esté perdiendo capacidad de absorber choques.",
        "en": "Taken together, the indicators this panel tracks are behaving predictably. There's no broad-based sign, for now, that the economy is losing its ability to absorb shocks.",
    },
    "monitor": {
        "es": "Varios de los indicadores que monitorea este panel muestran cierta inestabilidad reciente, aunque no de forma generalizada. Es un momento para seguir de cerca la evolución, no para sacar conclusiones todavía.",
        "en": "Several of the indicators this panel tracks show some recent instability, though not broadly across the board. This is a moment to keep watching closely, not to draw conclusions yet.",
    },
    "fragile": {
        "es": "Varios de los indicadores que monitorea este panel muestran, de forma consistente y estadísticamente significativa, un comportamiento cada vez menos predecible. Esto no significa que una crisis sea inevitable — significa que el sistema está absorbiendo más presión de la habitual, y vale la pena prestarle atención sostenida, no solo puntual.",
        "en": "Several of the indicators this panel tracks show a consistently, statistically significant pattern of becoming less predictable. This doesn't mean a crisis is inevitable — it means the system is absorbing more pressure than usual, and it's worth paying sustained, not just occasional, attention to it.",
    },
}


def get_composite_stakeholder_explanation(status_id: str, lang: str) -> str:
    try:
        return COMPOSITE_STAKEHOLDER_EXPLANATIONS[status_id][lang]
    except KeyError as e:
        raise KeyError(f"No composite stakeholder explanation for status_id='{status_id}', lang='{lang}'") from e